# Generated by Django 2.2.4 on 2020-01-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twofa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofauser',
            name='need2fa',
            field=models.BooleanField(default=True),
        ),
    ]
